version: 2

jobs:
  build:
    macos:
      xcode: "9.0.0"
    environment:
      CIRCLE_TEST_RESULTS: $HOME/test-results
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout

      - run:
          name: Check PR Metadata
          command: bundle exec danger || echo "danger failed"

      - run: bundle exec fastlane test
